server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Kolkata
  jackson:
    time-zone: Asia/Kolkata

  mail:
    host: ${MAIL_HOST}         # For Gmail; or your SMTP server
    port: ${MAIL_PORT}         # 587 for TLS, 465 for SSL
    username: ${MAIL_USERNAME}  # Your email address
    password: ${MAIL_PASSWORD}  # Or typical email password, or app-specific password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
