// File: EmployeeResponseDTO.kt
package com.example.employee_management.dto

import com.example.employee_management.model.EmploymentType
import com.example.employee_management.model.EmployeeStatus
import com.example.employee_management.model.WorkMode
import java.time.LocalDate
import java.util.*

data class EmployeeResponseDTO(
    val id: Long?,
    val employeeId: UUID,
    val microsoftId: String?,
    val firstName: String,
    val lastName: String,
    val middleName: String?,
    val dateOfBirth: LocalDate,
    val gender: String?,
    val nationality: String?,
    val maritalStatus: String?,
    val photoPath: String?,
    val workEmail: String,
    val personalEmail: String?,
    val mobileNumber: String,
    val alternatePhoneNumber: String?,
    val currentAddress: String?,
    val permanentAddress: String?,
    val emergencyContactName: String?,
    val emergencyContactNumber: String?,
    val jobTitle: String,
    val department: String,
    val managerName: String?,
    val dateOfJoining: LocalDate,
    val employmentType: EmploymentType,
    val employeeStatus: EmployeeStatus,
    val workMode: WorkMode,
    val officeLocation: String?,
    val employeeCode: String,
    val skills: String?,
    val certifications: String?,
    val education: String?,
    val previousExperience: String?,
    val projects: String?,
    val languagesKnown: String?,
    val linkedInUrl: String?,
    val githubUrl: String?,
    val portfolioUrl: String?,
    val salary: Double?,
    val bankAccountNumber: String?,
    val panNumber: String?,
    val pfNumber: String?,
    val insuranceDetails: String?,
    val bonusAmount: Double?,
    val attendanceRecord: String?,
    val leaveBalance: Int,
    val leaveHistory: String?,
    val shiftTiming: String?,
    val performanceRating: Double?,
    val appraisalHistory: String?,
    val goals: String?,
    val trainingsAttended: String?,
    val resumePath: String?,
    val offerLetterPath: String?,
    val experienceLettersPath: String?,
    val idProofPath: String?,
    val addressProofPath: String?,
    val systemUsername: String?,
    val systemRole: String,
    val badgeId: String?,
    val bloodGroup: String?,
    val tShirtSize: String?,
    val hobbies: String?,
    val vehicleDetails: String?,
    val remarks: String?,
    val aadhaarNumber: String,
    val active: Boolean
)